apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuard
    spec:
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Exists"
          effect: "NoSchedule"
      # nodeSelector:
      #   type: virtual-kubelet
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          # ports:
          #   - containerPort: 8080
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: 200m
